---
".gitlab-ci.yml":
  delete: true
".rubocop.yml":
  default_configs:
    inherit_from: ".rubocop_todo.yml"
".travis.yml":
  global_env:
  - HONEYCOMB_WRITEKEY="7f3c63a70eecc61d635917de46bea4e6",HONEYCOMB_DATASET="litmus
    tests"
  deploy_to_forge:
    enabled: false
  simplecov: true
  notifications:
    slack:
      secure: AlI3PETMDYeUke1uxWTNSoWYoG8edaPi/h0WgjSZvE72SJqwmxWIjP9hOfzzrefiKBsLT4PZdkuCuOuW22g/FAQ8xMwk1S4Vt/eu42KCYE5SSYtKgqO4XvzNqWflB52BfDsDh84W7eJzb2hMIhIrGido2RIs7oqpGJ//xi9xZAY=
appveyor.yml:
  environment:
    HONEYCOMB_WRITEKEY: 7f3c63a70eecc61d635917de46bea4e6
    HONEYCOMB_DATASET: litmus tests
  simplecov: true
  use_litmus: true
  matrix_extras:
  - RUBY_VERSION: 25-x64
    ACCEPTANCE: 'yes'
    TARGET_HOST: localhost
  - RUBY_VERSION: 25-x64
    ACCEPTANCE: 'yes'
    TARGET_HOST: localhost
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
Gemfile:
  use_litmus: true
  optional:
    ":development":
    - gem: net-telnet
      version: 0.1.0
      condition: Gem::Version.new(RUBY_VERSION.dup) < Gem::Version.new('2.3.0')
    - gem: net-telnet
      condition: Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.3.0')
    - gem: github_changelog_generator
      git: https://github.com/skywinder/github-changelog-generator
      ref: 20ee04ba1234e9e83eb2ffb5056e23d641c7a018
      condition: Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')
    - gem: rspec-puppet
      require: true
      git: https://github.com/rodjek/rspec-puppet
    - gem: puppet_litmus
      require: true
      git: https://github.com/puppetlabs/puppet_litmus
    - gem: bolt
      version: "= 2.23.0"
      condition: Gem::Version.new(RUBY_VERSION.dup) > Gem::Version.new('2.5.0')
Rakefile:
  requires:
  use_litmus_tasks: true
spec/spec_helper.rb:
  mock_with: ":rspec"
  coverage_report: true
